### ISSUE TITLE
Issue in setting up telos

### ISSUE THREAD

**Issue by samarthgaur** [Telos-Foundation/telos#44]
Hi All,

I am facing issue while setting up the telos on my server. While running the below command, I get the message as "Telos source either doesn't exist, or isn't initialized". Here my genesis file is blank. Please help me in resolving this issue.

grow spin single myname1234 [my-server-ip] path/to/genesis.json testnet.telosfoundation.io:6789

**Comment by ARoomWithABue** [comment]
Please move any bugs related to the grow tool, to https://github.com/Telos-Foundation/grow.

The reason your command is failing is because your telos source directory hasn't been saved in the `state.json` file for grow. Try running, `grow init setsource /path/to/telos/source` If this issue continues after that please reopen this issue in the repository previous mentioned.
