### ISSUE TITLE
Irregularity between the monitor and rotations table

### ISSUE THREAD

**Issue by jbuice** [Telos-Foundation/telos#48]
We're seeing irregularity between the monitor and rotations table. Currently have zalmoxisdeus producing from position 30 but the table says:

> {
  "rows": [{
      "bp_currently_out": "telasiachina",
      "sbp_currently_in": "telosintasia",
      "bp_out_index": 5,
      "sbp_in_index": 29,
      "next_rotation_time": "2018-08-31T17:29:12.500",
      "last_rotation_time": "2018-08-31T11:29:12.500"
    }
  ],
  "more": false
}

**Comment by ARoomWithABue** [comment]
I'll take a look at this today and get back to you.

**Comment by jrjackso** [comment]
I'm pretty sure this is fixed by #88 
Previously sbp_currently_in (telosintasia) could be inconsistent with the sbp that made it into top_producers in the following code:

`if (it_sbp->producer_name == prods[_grotations.sbp_in_index].producer_name)
          top_producers.emplace_back(*it_sbp);
else
          top_producers.emplace_back(prods[_grotations.sbp_in_index]);`

In other words, if it_sbp->producer_name (telosintasia) wasn't equal to prods[_grotations.sbp_in_index].producer_name (zalmoxisdeus) it would put zalmoxisdeus in.
(note: the order of prods changes by vote weight)
