### ISSUE TITLE
Teclos Command Not Found

### ISSUE THREAD

**Issue by samarthgaur** [Telos-Foundation/telos#49]
Hi All,

I have setup a node and followed all the steps as provided in telos github link. Post registration when I run the regproducer command, it says 'teclos command not found'. Please help me in resolving this issue.

**Comment by ARoomWithABue** [comment]
Get in terminal, change directory to the telos source folder. Run `sudo ./telos_install.sh`. That is an error in the instructions, and I'll make sure we correct that today. The installation script creates symbolic likes in your `/usr/local/bin` that are used for creating a link in your `PATH` variable. Since you didn't run the installation script a `teclos` executable wasn't found in any folder specified by your `PATH` variable.
