### ISSUE TITLE
LIB Advancing with less than 15 BPs registered

### ISSUE THREAD

**Issue by jbuice** [Telos-Foundation/telos#8]
There are only 14 BPs currently producing but LIB continues to advance. It would appear that we did have 15 BPs registered at one point, but Telos Miami un-reg and the chain kept moving. 

![image](https://user-images.githubusercontent.com/16478426/43266818-f244e1e2-90b1-11e8-9cbb-dae249bcb91d.png)
I also unregprod to take BP count down to 13 to see what happens and LIB continued to move without consensus.

**Comment by craigbranscom** [comment]
This is actually the expected behavior. The network is still at consensus because the 2/3 +1 consensus algorithm isn't hardcoded to 21, it's subjective based on the number of registered producers. If there are 15 registered BP's, then the network only needs 11 BP's to achieve consensus.

@ARoomWithABue found the code that confirms this in [controller.cpp](https://github.com/Telos-Foundation/telos/blob/f537fc2fe25efc380a2e3052019d80b4c34d17d3/libraries/chain/controller.cpp#L1025).
